### ISSUE TITLE
Support for select2 inputs?

### ISSUE THREAD

**Issue by matheusfc09** [geminilabs/float-labels.js#15]
Do you think about adapting this library for select2. Thanks!

**Comment by pryley** [comment]
Float-labels uses javascript to wrap form fields in a parent DIV and adds/removes/toggles classes on field state change. It then uses CSS styles to style the field on state changes.

Select2 changes the DOM, toggles classes on state change, _hides the select field_, and uses CSS to style the faux-select field.

Float-labels does not need to adapt for select2, you simply need to use the "exclude" option that float-labels provides to exclude the SELECT field that is used with the Select2 library. Once you have done that, you can add your own custom CSS to target the select2 classes to imitate float-labels.
