### ISSUE TITLE
Setting field value through javascript doesn't show the label

### ISSUE THREAD

**Issue by schellenbergk** [geminilabs/float-labels.js#19]
Hello, great plugin by the way....

When I set the field value using javascript the label does not show up.  I've tried triggering change event too but no success.

```
input.value = val;
input.dispatchEvent(new Event('change'));
```
However I was able to use this workaround but see if there is a way of updating float-labels so workaround is not needed... Thanks...

```
input.value = val;
el.parentNode.classList.add('fl-is-active');
```

**Comment by pryley** [comment]
Try this:
```js
input.value = val;
input.dispatchEvent(new Event('input'));
```
