### ISSUE TITLE
Incorrect function name

### ISSUE THREAD

**Issue by DevinWalker** [geminilabs/float-labels.js#2]
Why is this named `$.fn.starrating`? https://github.com/geminilabs/float-labels.js/blob/master/src/float-labels.js#L296

**Comment by pryley** [comment]
Oh thanks @DevinWalker, it's some left over code I copy-pasted from [star-rating.js](https://github.com/geminilabs/star-rating.js) when migrating the jQuery code to vanilla.

**Comment by pryley** [comment]
Thanks @DevinWalker, it's code leftover from [star-rating.js](https://github.com/geminilabs/star-rating.js) used when migrating from jQuery to vanilla.

Sloppy...

Should be fixed in v2.0.1
