### ISSUE TITLE
Module Support

### ISSUE THREAD

**Issue by schellenbergk** [geminilabs/float-labels.js#21]
Hey, Great Plugin, however, would be nice if you added module support... Should not be much work.  It would be nice to just:
```
import FloatLabels from 'float-labels.js';
```

I think all you have to do is duplicate `float-labels.js/src/float-labels.js` -> `float-labels.js/src/float-labels-module.js` and remove:
```
;(function( window, document, undefined )
{
	"use strict";
//and
})( window, document );
```

and replace:

```
window.FloatLabels = Plugin;
```
with
```
export default Plugin;
```

Thanks!

**Comment by pryley** [comment]
see v3.3.3 8d04e05
