### ISSUE TITLE
Bundling float-labels.js with webpack

### ISSUE THREAD

**Issue by wolfisdev** [geminilabs/float-labels.js#25]
Hi,

I'm trying to bundle the float-labels.js plugin into my JS with webpack. 
I tried several approaches but didn't get anything to work. I installed it with

`
npm install --save float-labels.js
`

My app.js looks as following

```
...
require('jquery-ui/ui/widgets/autocomplete');

require('bootstrap-datepicker');
require('float-labels.js');

require('./my-script');
...
```

This leaves me with the following error

`
TypeError: $(...).autocomplete is not a function
`

Before, I just downloaded your .js and added a corresponding script tag to my markup and it worked, but I'd like to bundle it with my own script now. Maybe you can help me :) ?

Thanks in advance!

**Comment by pryley** [comment]
Looks like the error is referring to: `require('jquery-ui/ui/widgets/autocomplete');`

Perhaps these will be of help: 

https://webpack.js.org/configuration/resolve/
https://stackoverflow.com/questions/40873599/typeerror-webpack-require-i-is-not-a-function#48296579
https://stackoverflow.com/questions/16300586/typeerror-autocomplete-is-not-a-function

**Comment by wolfisdev** [comment]
Thank you for your response, ofc it's not a float label problem. When I re-read my question I can't imagine why I opened this issue here...

Sorry for bothering you!
