### ISSUE TITLE
Object doesn't support property or method 'forEach' error IE11

### ISSUE THREAD

**Issue by agnertorres** [geminilabs/float-labels.js#3]
IE version: 11.0.9600.18697 windows 7

![ie-float-label-error](https://user-images.githubusercontent.com/18406441/28184678-b289fab0-67ea-11e7-88d5-007a6b4462dd.jpeg)

**Comment by agnertorres** [comment]
I think I solved this issue, but I can't build your project to send you a pull request.
Console show me that error:

![sass-error](https://user-images.githubusercontent.com/18406441/28190086-814bac68-67ff-11e7-8be4-64f18538ad45.jpeg)

**Comment by agnertorres** [comment]
This changes works for me on IE.
I just make changes in the functions Init() and onReset(), and put this lines before the forEach

- init(): ` var array = [].slice.call( form.querySelectorAll( tag + exclude ) ); `

- onReset(): ` var array = [].slice.call( ev.target.querySelectorAll( tag ) ); `



follow this pictures:

![init-float-label](https://user-images.githubusercontent.com/18406441/28190438-48a85a08-6801-11e7-8e87-d0ec5d150485.jpeg)

![onreset-float-label](https://user-images.githubusercontent.com/18406441/28190530-bc43f300-6801-11e7-83a8-f38c4bad4d00.jpeg)

**Comment by pryley** [comment]
Fixed in v2.0.2, thanks. Gulp should now also compile correctly.

**Comment by agnertorres** [comment]
Thanks for fix this! 
npm still installing v2.0.1. Please, can you notice me when v2.0.2 is available in npm?

**Comment by pryley** [comment]
should be available now

**Comment by agnertorres** [comment]
Thanks!
