### ISSUE TITLE
get attribute value in modal dialog

### ISSUE THREAD

**Issue by wagnerfillio** [geminilabs/float-labels.js#31]
I have searched, and found something close to my problem, but it did not solve # 14.

Using a Modal Dialog, I was unsuccessful in displaying the field label.

As the field was populated via an ajax (json) return. its value attribute is always empty.

How can I check this case and display the label correctly for modal dialog?

![lbl](https://user-images.githubusercontent.com/22008303/51136404-8ec97480-1823-11e9-9c8f-1c7505a1dfa0.png)

**Comment by pryley** [comment]
Have you tried triggering a rebuild after the ajax return and a value is added?

i.e. `floatlabels.rebuild()`

Please see the usage section in the readme.

**Comment by wagnerfillio** [comment]
Here's how I did it.
I declared the variable:

`var floatlabels;`

Inside the `ready` event I wrote the function:

`floatlabels = new FloatLabels( 'frm-receita', {
      style: 1,
});`

and after the successful ajax response, I added:
`floatlabels.rebuild();`

But it still does not work!!

**Comment by pryley** [comment]
send me a link

**Comment by wagnerfillio** [comment]
Hello, playing a page to put the example, I found out where the problem was, do not just add `floatlabels.rebuild ()` in the ajax return.
In my case, it was necessary to add after the `objeto_form(); `

`success: (function (objeto) {
	objeto_aviso = objeto;
        objeto_form();
        floatlabels.rebuild();
         ret = true;
}),`

**Comment by pryley** [comment]
Please close the issue if it is solved.

**Comment by wagnerfillio** [comment]
thank you
