### ISSUE TITLE
ng-model issue in angularjs

### ISSUE THREAD

**Issue by gtopsis** [geminilabs/float-labels.js#32]
```
<form>
   <input type="text" id="test" ng-model="vm.user.test">
   <label for="test">Test</label>
</form>
```

and inside my class constructor

```
window.floatlabels = new window.FloatLabels('form', {
      // options go here,
      style: 1
});
```

Although the plugin works ok with the above example (I have a float label) I lose the connection with ng-model. More specifically, the value of vm.user.test is not updated anymore.

Before add this plugin everything was working. Any idea how this plugin affects the above simple case ?

**Comment by pryley** [comment]
I have not used angular with float-labels so am unable to assist you. 
Please see #33 , perhaps this is related.

**Comment by gtopsis** [comment]
After 2 days I am not sure what was the error, but I loaded the plugin on script tag instead of class constructor and for now it works. 

thanks for the tool and the fast reply
