### ISSUE TITLE
float-labels.js plugin and datepicker

### ISSUE THREAD

**Issue by wagnerfillio** [geminilabs/float-labels.js#33]
I am using a field in the format `datepicker`.

When you manually enter a date, it works fine.

But when using select a date by `datepicker`, the label does not work.

![data](https://user-images.githubusercontent.com/22008303/51347495-62159700-1a87-11e9-808e-d421acf7c78e.png)

**Comment by pryley** [comment]
Float Labels listens for the standard [input](https://developer.mozilla.org/en-US/docs/Web/Events/input) event to detect changes. If the datepicker package you are using does not trigger the input event on change, then you will need to handle this yourself by either [triggering the input event](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) or rebuilding float-labels on datepicker change.

**Comment by wagnerfillio** [comment]
Ah some way to change the default input to detect changes?

Change to click event?

For example:
It would be necessary to click inside the field to activate the floating label.

I believe that I could change these three functions:

`onBlur_`,  `onInput_` and `onFocus_`

**Comment by pryley** [comment]
I suggest you search the issues (open and closed) on the datepicker github as there is likely a similar issue there.
