### ISSUE TITLE
Replacing colon with empty string

### ISSUE THREAD

**Issue by Timu57** [geminilabs/float-labels.js#34]
Is there a reason why the colons in the label text are replaced with an empty string in line 152 by the getLabelText method?
I removed the replacing to test if it breaks something but everything worked fine.
I need to show a url, with https:// prefixed, to the user.

Thank you in advance
#35

**Comment by pryley** [comment]
It removes an asterisk in case this has been added to the label to denote a required field.

I am unsure why the colon is there, this was added in v1.0.7 however I no longer remember the reason.
