### ISSUE TITLE
Label active when element is in focus

### ISSUE THREAD

**Issue by wagnerfillio** [geminilabs/float-labels.js#37]
Hi, is there any way to change the behavior of the plugin so that the label fires when there is focus on the element?

![modal](https://user-images.githubusercontent.com/22008303/61735997-85cdd880-ad5b-11e9-87d6-f934ff481868.png)

**Comment by pryley** [comment]
Once a field has been transformed by float-labels, the wrapping div is given different CSS classes on state change:

On the focus event: `.fl-has-focus`
On the input event: `.fl-is-active`

The rest is controlled by CSS.

So all you would need to do is extend the CSS to apply the `.fl-is-active` CSS to the `.fl-has-focus` CSS.

**Comment by wagnerfillio** [comment]
very good, thanks for the quick return!!
