### ISSUE TITLE
(Bug) Autocomplete 

### ISSUE THREAD

**Issue by cvaize** [geminilabs/float-labels.js#38]
![image](https://user-images.githubusercontent.com/26907947/68610001-8d66e800-04d8-11ea-88d5-6be6625a387f.png)
[Fix](https://github.com/cvaize/detect-autofill)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/68610074-bdae8680-04d8-11ea-9c06-cdc0df2bb334.png)

![image](https://user-images.githubusercontent.com/26907947/68610100-cf902980-04d8-11ea-978d-04a34881ee4e.png)

**Comment by cvaize** [comment]
https://github.com/cvaize/detect-autofill

**Comment by pryley** [comment]
This package will no longer be updated. Please use https://github.com/anydigital/float-label-css instead.
