### ISSUE TITLE
Not Used floatlabels.rebuild();

### ISSUE THREAD

**Issue by wagnerfillio** [geminilabs/float-labels.js#39]
It is possible not to use `float labels.rebuild ();` after returning from ajax?
maybe run only once and automatically recognize an active field ?

**Comment by pryley** [comment]
For what reason? You only need to run rebuild if you are changing the form fields with ajax (i.e. swapping out fields with ajax when toggling payment methods in an ecommerce form)

**Comment by wagnerfillio** [comment]
maybe it's a repetitive job, whenever there is a request, I have to rebuild it.
It would be a way to leave less manual labor!

If I return a json object from the request and want to fill in a Modal Bootstrap, for example, after filling in the modal, I need to rebuild.

if there is any way, I would like you to help me with any idea

**Comment by pryley** [comment]
If you are using ajax to fill in the field values of a form, you do not need to rebuild the float label DOM, you just need to manually trigger the input event (or change event with SELECT) .

```js
el.value = "hello";  
el.dispatchEvent(new Event('input'));
```
